Vagrant.configure("2") do |config|
  config.vm.define :servidor do |servidor|
    servidor.vm.box = "bento/centos-7.9"
    servidor.vm.network :private_network, ip: "192.168.50.4"
    servidor.vm.hostname = "servidor"
  end
end