Vagrant.configure("2") do |config|
  config.vm.define :servidor do |servidor|
    servidor.vm.box = "vargas_insuasti/servidor"
    servidor.vm.box_version = "3.0.0"
    servidor.vm.network :private_network, ip: "192.168.50.3"
    servidor.vm.network "forwarded_port", guest: 80, host: 3000
    servidor.vm.hostname = "servidor"
  end
end